name: flutter_cookie_bridge
description: A Flutter plugin that synchronizes cookies between network requests and WebViews.
version: 1.0.23
repository: https://github.com/spense-fintech/flutter_cookie_bridge
issue_tracker: https://github.com/spense-fintech/flutter_cookie_bridge/issues
environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: '>=3.1.0'

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  plugin_platform_interface: ^2.1.8
  shared_preferences: ^2.2.2
  url_launcher: ^6.0.20
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  device_info_plus: ^11.2.2
  http: ^1.3.0
  open_filex: ^4.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: money.spense.flutter_cookie_bridge
        pluginClass: FlutterCookieBridgePlugin
      ios:
        pluginClass: FlutterCookieBridgePlugin

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package