include: package:flutter_lints/flutter.yaml

linter:
  rules:
    constant_identifier_names: ignore
    deprecated_member_use_from_same_package: ignore

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
analyzer:
  errors:
    deprecated_member_use: ignore
    deprecated_member_use_from_same_package: ignore
    unnecessary_cast: ignore
    unnecessary_import: ignore
